# Generated by Django 6.0.5 on 2026-06-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text="What's need to be done?")),
                ('completed', models.BooleanField(default=False, help_text='Is this task finished?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When was this task added?')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When was this last changed?')),
                ('due_date', models.DateField(help_text='When does this need to be done?', null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=100)),
                ('category', models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Shopping', 'Shopping'), ('Health', 'Health'), ('Other', 'Other')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Todo Task',
                'verbose_name_plural': 'Todo Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
