# Generated by Django 6.0.5 on 2026-06-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, help_text='When does this need to be done?', null=True),
        ),
    ]
