# Generated by Django 6.0.5 on 2026-06-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Shopping', 'Shopping'), ('Health', 'Health'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(help_text="What's need to be done?", max_length=250),
        ),
    ]
